// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'your-api-key',
    appId: 'your-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    authDomain: 'your-project-id.firebaseapp.com',
    storageBucket: 'your-project-id.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHX5531r3N2JmWfGl_m6Rx8f1O6A_8px4',
    appId: '1:991318587825:android:f78230515df7f07f12e590',
    messagingSenderId: '991318587825',
    projectId: 'sinflix-6cf46',
    storageBucket: 'sinflix-6cf46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0rVjKJbxgSCzjNe5aWwXyukdpdTzkZl8',
    appId: '1:991318587825:ios:031320df686c304412e590',
    messagingSenderId: '991318587825',
    projectId: 'sinflix-6cf46',
    storageBucket: 'sinflix-6cf46.firebasestorage.app',
    iosClientId:
        '991318587825-031320df686c304412e590.apps.googleusercontent.com',
    iosBundleId: 'com.example.caseStudy',
  );
}
